#!/usr/bin/env bash

FILES=$1*.c
i=1

for f in $FILES
do
    echo "$i.Compiling $f - "

    ./ccomp -d lsp -o $f.out $f

    mkdir $f_outputs
    mv $f.* $f_outputs/

    echo "  Tokens written to $f.tok"
    echo "  Reductions written to $f.red"
    echo "  Scanner debug output written to $f.ldb"
    echo "  Parser debug output written to $f.ydb"
    echo "  Compiler output written to $f.out"
    echo ""

    ((i++))
done
